compile:
	pdflatex slides.tex
	pdflatex slides.tex
	rm *.toc *.aux *.log *.nav *.snm *.out *.vrb 

compile_spanish:
	pdflatex slides_spanish.tex
	pdflatex slides_spanish.tex
	rm *.toc *.aux *.log *.nav *.snm *.out *.vrb
